name: home
timestamp: 1593342611
version: 7
preset:
  image: 'gantry-admin://images/layouts/home.png'
  name: home
  timestamp: 1588214942
positions:
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  showcase: Showcase
  feature: Feature
  subfeature: Subfeature
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  menu:
    menu-1309: Menu
  sample:
    sample-1: 'Gantry 5'
    sample-2: 'Getting Started'
    sample-3: 'Key Features'
  messages:
    system-messages-8618: 'System Messages'
  position:
    position-footer: Footer
  copyright:
    copyright-3586: Copyright
  social:
    social-1633: Social
  branding:
    branding-7294: Branding
  mobile-menu:
    mobile-menu-2771: 'Mobile Menu'
inherit: {  }
