version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1588214942
layout:
  /header/:
    -
      - 'logo-9722 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-9544
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-5032
    -
      - system-content-9620
  /footer/:
    -
      - position-footer
    -
      - 'copyright-6796 40'
      - 'spacer-5084 30'
      - 'branding-2844 30'
  offcanvas:
    -
      - mobile-menu-7345
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
