name: _body_only
timestamp: 1593342611
version: 7
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1588214942
positions:
  header: Header
  breadcrumbs: Breadcrumbs
  footer: Footer
sections:
  header: Header
  navigation: Navigation
  main: Main
  footer: Footer
  offcanvas: Offcanvas
particles:
  logo:
    logo-2033: Logo
  position:
    position-header: Header
    position-breadcrumbs: Breadcrumbs
    position-footer: Footer
  menu:
    menu-5808: Menu
  messages:
    system-messages-3187: 'System Messages'
  content:
    system-content-1698: 'Page Content'
  copyright:
    copyright-9066: Copyright
  spacer:
    spacer-6481: Spacer
  branding:
    branding-4248: Branding
  mobile-menu:
    mobile-menu-2128: Mobile-menu
inherit: {  }
