version: 2
preset:
  image: 'gantry-admin://images/layouts/default.png'
  name: default
  timestamp: 1588214942
layout:
  /header/:
    -
      - 'logo-2033 30'
      - 'position-header 70'
  /navigation/:
    -
      - menu-5808
  /main/:
    -
      - position-breadcrumbs
    -
      - system-messages-3187
    -
      - system-content-1698
  /footer/:
    -
      - position-footer
    -
      - 'copyright-9066 40'
      - 'spacer-6481 30'
      - 'branding-4248 30'
  offcanvas:
    -
      - mobile-menu-2128
structure:
  header:
    attributes:
      boxed: ''
  navigation:
    type: section
    attributes:
      boxed: ''
  main:
    attributes:
      boxed: ''
  footer:
    attributes:
      boxed: ''
content:
  position-header:
    attributes:
      key: header
  position-breadcrumbs:
    attributes:
      key: breadcrumbs
  position-footer:
    attributes:
      key: footer
